### ISSUE TITLE
Create dash movement option

### ISSUE THREAD

**Issue by Ryan17Lewis** [ramawama/In-The-Shadows#227]

**Comment by ramawama** [comment]
~4 hours, works need to limit user movement so they cant spam dash

**Comment by Ryan17Lewis** [comment]
Fixed regular animation (frames weren't being cycled through and direction wasnt changing before movement) ~ 2 hrs

**Comment by Ryan17Lewis** [comment]
Dash anim added. Needs some tweaking ~ 1 hr

**Comment by ramawama** [comment]
Added dash counter so can only be used after three turns, displays current counter in inventory rn ~3 hours

**Comment by ramawama** [comment]
TOFIX: dash resets cooldown even if u walk into wall, should disable dash if there's no open space

**Comment by ramawama** [comment]
TOFIX: should also be able to click space again and disable dash + have indication that dash is currently active
