### ISSUE TITLE
📂 persistent features

### ISSUE THREAD

**Issue by pkyu** [ramawama/In-The-Shadows#252]
probably just make a txt file that saves what level ur on and gitignore it

**Comment by ramawama** [comment]
~ 3 hours

**Comment by ramawama** [comment]
Reopened to encompass more persistent features, such as total turns used and windowed/fullscreen options

**Comment by ramawama** [comment]
Will work on windowed/ fullscreen then turn counter

**Comment by ramawama** [comment]
turn torches stats persistent - 2 hours

**Comment by ramawama** [comment]
persistent - level, difficuluty , torches, items, and music. +1 hour
